name       : mathjax2
version    : 2.7.9
release    : 1
source     :
    - https://github.com/mathjax/MathJax/archive/refs/tags/2.7.9.tar.gz : c9167279c87da044f2ff910ad573a02ce90354cb59440ae568eb86e1630f65df
license    : GPL-2.0-or-later
component  : office.scientific
summary    : Beautiful and accessible math in all browsers
description: |
    MathJax is an open-source JavaScript display engine for LaTeX, MathML, and AsciiMath notation that works in all modern browsers. It was designed with the goal of consolidating the recent advances in web technologies into a single, definitive, math-on-the-web platform supporting the major browsers and operating systems. It requires no setup on the part of the user (no plugins to download or software to install), so the page author can write web documents that include mathematics and be confident that users will be able to view it naturally and easily. Simply include MathJax and some mathematics in a web page, and MathJax does the rest.
setup      : |
    rm -r docs test unpacked
    rm -r fonts/HTML-CSS/TeX/png
    for _format in eot otf svg ; do
        find . -type d -name "$_format" -prune -exec rm -rf {} \;
    done
install    : |
    mkdir -p $installdir/usr/share/{fonts,licenses/mathjax2}
    cp -a $workdir $installdir/usr/share/mathjax2
    mv $installdir/usr/share/mathjax2/fonts $installdir/usr/share/fonts/mathjax2
    ln -s /usr/share/fonts/mathjax2 $installdir/usr/share/mathjax2/fonts
